{
    train_split: ./Riseholme-2021/Splits/Split1/Split1-R-Train.txt,
    val_split: ./Riseholme-2021/Splits/Split1/Split1-R-Val.txt,
    test_split: ./Riseholme-2021/Splits/Split1/Split1-R-Test.txt, 
    
    normal_dir: ./Riseholme-2021/Data/Normal,
    anomalous_dir: ./Riseholme-2021/Data/Anomalous,
    anomalous_ext: png, # File extension of anomalous images
    img_size: 64, # Target size to resize loaded images

    n_processors: 1, # Number of processes to augment data
    lr: .000005, # Learning rate
    fc_feat: True, # Extract features from FC layer (True) or Conv layer (False)
    
    n_epochs: 1500,
    val_interval: 30,
    test_interval: 30,
    n_neighbors: [1, 3, 5, 10], # Numbers of neighbors for distance calculation
    epoch_size: 8, # Number of batch updates per epoch
    batch_size: 128, 
    ch_label: False, # Get labels from 0 to number of possibilities

    aug_mode: CH-Rand, # {CH-Rand, CH-Perm, CH-Split, CutPaste}
    portion: 1., # Portion of pixels to apply augmentation in CH-Rand, CH-Perm, CH-Split
    
    tensorboard_dir: ./tb_logs,
    model_dir: ./saved_models,
    val_acc_threshold: .95, # Val_acc threshold for stopping criterion
    stop_criterion: 5, # Stop training if this many times val_acc exceeds threshold in a row

    test:{
        model_path: ./saved_models/20211001-201050.h5,
    }
}